version: "3.7"
services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ferris
      MONGO_INITDB_ROOT_PASSWORD: rusty
    networks:
      - mongo-network

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: ferris
      ME_CONFIG_MONGODB_ADMINPASSWORD: rusty
    depends_on:
      mongo:
        condition: service_started
    networks:
      - mongo-network

networks:
  mongo-network:
    driver: bridge

