version: "3.7"
services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ferris
      MONGO_INITDB_ROOT_PASSWORD: rusty
